name: Build Solutions

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Install packages
      run: sudo apt -y install gcovr

    - name: Checkout
      uses: actions/checkout@v3

    - name: Update cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '4.1.x'

    - name: Generate Project
      run: cmake -B build/ -S . --preset gcc14

    - name: Build
      run: cmake --build build/

    - name: Run all test executables
      run: |
        find ./build/2015 -type f -executable | while read -r exe; do
        echo "Running $exe"
        "$exe" || "Failed: $exe"
        done

    - name: Generate Code Coverage
      run: gcovr --exclude build/ --gcov-executable gcov-14

    - uses: codecov/codecov-action@v4
      with:
        fail-ci-if-error: false
        name: codecov
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true

